---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  DBSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: 'how-bootcamp-encontro-7-ingestao-de-dados-rds-credentials'
      Description: 'This is a secret for the RDS DB instance'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "app_data_lake"}'
        GenerateStringKey: 'password'
        PasswordLength: 30
        ExcludeCharacters: '"@/\\'

  DMSRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - 'dms.amazonaws.com'
            Action: 
              - 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: 'DMSAccessToS3'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 's3:*'
                Resource: '*'

  MyDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: '20'
      DBInstanceClass: 'db.t3.micro'
      Engine: 'postgres'
      EngineVersion: '14'
      MasterUsername: 
        'Fn::Sub': '{{resolve:secretsmanager:${DBSecret}::username}}'
      MasterUserPassword: 
        'Fn::Sub': '{{resolve:secretsmanager:${DBSecret}::password}}'
      DBName: 'postgres'

  MyBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 
        Fn::Sub: '${AWS::AccountId}-${AWS::StackName}'

  DMSInstance:
    Type: 'AWS::DMS::ReplicationInstance'
    Properties: 
      ReplicationInstanceIdentifier: 'encontro-7-ingestao-de-dados-dms'
      ReplicationInstanceClass: 'dms.t2.micro'
      AllocatedStorage: 20
      PubliclyAccessible: False
      MultiAZ: False

  SourceEndpoint:
    Type: 'AWS::DMS::Endpoint'
    Properties:
      EndpointIdentifier: 'source-endpoint'
      EndpointType: 'source'
      EngineName: 'postgres'
      ExtraConnectionAttributes: 'PluginName=pglogical'
      Password: 
        'Fn::Sub': '{{resolve:secretsmanager:${DBSecret}::password}}'
      Username:
        'Fn::Sub': '{{resolve:secretsmanager:${DBSecret}::username}}'
      ServerName: 
        Fn::GetAtt: [ 'MyDB', 'Endpoint.Address' ]
      Port: 5432
      ServiceAccessRoleArn:
        Fn::GetAtt: [ 'DMSRole', 'Arn' ]

  DMSTask:
    Type: 'AWS::DMS::ReplicationTask'
    Properties: 
      MigrationType: 'full-load'
      ReplicationInstanceArn: 
        Fn::GetAtt: [ 'DMSInstance', 'ReplicationInstanceArn' ]
      SourceEndpointArn: 
        Fn::GetAtt: [ 'SourceEndpoint', 'Arn' ]
      TargetEndpointArn: 
        Fn::GetAtt: [ 'MyBucket', 'Arn' ]
      TableMappings: 
        Fn::Sub: |
          {
            "rules": [
              {
                "rule-type": "selection",
                "rule-id": "1",
                "rule-name": "1",
                "object-locator": {
                  "schema-name": "%",
                  "table-name": "%"
                },
                "rule-action": "include"
              }
